#define UI_free_InitOptions(ptr) free(ptr)

//// Seems like we'll need to call destroy on these manually
//#define UI_free_Area(ptr) uiControlDestroy(ptr)
//#define UI_free_Box(ptr) uiControlDestroy(ptr)
//#define UI_free_Button(ptr) uiControlDestroy(ptr)
//#define UI_free_Checkbox(ptr) uiControlDestroy(ptr)
//#define UI_free_ColorButton(ptr) uiControlDestroy(ptr)
//#define UI_free_Combobox(ptr) uiControlDestroy(ptr)
//#define UI_free_DateTimePicker(ptr) uiControlDestroy(ptr)
//#define UI_free_EditableCombobox(ptr) uiControlDestroy(ptr)
//#define UI_free_Entry(ptr) uiControlDestroy(ptr)
//#define UI_free_FontButton(ptr) uiControlDestroy(ptr)
//#define UI_free_Form(ptr) uiControlDestroy(ptr)
//#define UI_free_Grid(ptr) uiControlDestroy(ptr)
//#define UI_free_Group(ptr) uiControlDestroy(ptr)
//#define UI_free_Label(ptr) uiControlDestroy(ptr)
//#define UI_free_MultilineEntry(ptr) uiControlDestroy(ptr)
//#define UI_free_ProgressBar(ptr) uiControlDestroy(ptr)
//#define UI_free_RadioButtons(ptr) uiControlDestroy(ptr)
//#define UI_free_Separator(ptr) uiControlDestroy(ptr)
//#define UI_free_Slider(ptr) uiControlDestroy(ptr)
//#define UI_free_Spinbox(ptr) uiControlDestroy(ptr)
//#define UI_free_Tab(ptr) uiControlDestroy(ptr)
//#define UI_free_Window(ptr) uiControlDestroy(ptr)
